services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: registre_securite_api
    command: npm run start:dev
    ports:
      - '${PORT:-3004}:${PORT:-3004}'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - NODE_ENV=dev

  db:
    image: postgres:16
    container_name: registre_securite_postgres
    ports:
      - '${POSTGRES_PORT:-5433}:5432'
    volumes:
      - registre_securite_pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}

volumes:
  registre_securite_pg_data:
