export enum Resources {
  USER = 'user',
  COMPANY = 'company',
  PLAN = 'plan',
  SITE = 'site',
  BUILDING = 'building',
  LOT = 'lot',
  PART = 'part',
  AUTH = 'auth',
  EQUIPMENT = 'equipment',
  INVENTORY = 'inventory',
  PRODUCT = 'product',
  INTERVENTION_TYPE = 'intervention-type',
  INTERVENTION = 'intervention',
  REPORT_TYPE = 'report-type',
  REPORT = 'report',
  ORGANIZATION = 'organization',
}
