export enum RoleType {
  ADMINISTRATOR = 'ADMINISTRATOR',
  COMPANY_ADMINISTRATOR = 'COMPANY_ADMINISTRATOR',
  COMPANY_MANAGER = 'COMPANY_MANAGER',
  COMPANY_MEMBER = 'COMPANY_MEMBER',
  VISITOR = 'VISITOR',
}
