export enum RoleType {
  ADMINISTRATOR = 'ADMINISTRATOR',
  CUSTOMER_ADMINISTRATOR = 'CUSTOMER_ADMINISTRATOR',
  CUSTOMER_MANAGER = 'CUSTOMER_MANAGER',
  CUSTOMER = 'CUSTOMER',
  VISITOR = 'VISITOR',
}
